spring.application.name=tiendaapp
server.port=8080

spring.thymeleaf.cache=false

# Variables de entorno con default para que arranque siempre

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tiendadb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate crea las tablas a partir de @Entity

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.com.ufide.tiendaapp=DEBUG
